services:
    chroma:
        image: chromadb/chroma:latest
        ports:
            - '8000:8000'
        env_file: .env
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=False
        networks:
            - schedulrai
        restart: unless-stopped
        container_name: chroma
        volumes:
            - .chroma_volume:/chroma/chroma

    backend:
        image: mikicv/schedulrai-backend:latest
        ports:
            - '3000:3000'
        container_name: backend
        pull_policy: always
        tty: true
        restart: unless-stopped
        networks:
            - schedulrai
        env_file: .env
        volumes:
            - .sqlite_volume:/app/data
            - .documents_volume:/app/documents
        environment:
            - CHROMA_SERVER_HOST=chroma
            - OLLAMA_API_BASE=host.docker.internal
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    frontend:
        image: mikicv/schedulrai-frontend:latest
        ports:
            - '80:80'
        environment:
            - VITE_API_URL=${VITE_API_URL}
        container_name: frontend
        restart: unless-stopped
        networks:
            - schedulrai
        depends_on:
            - backend
        pull_policy: always

networks:
    schedulrai:
        driver: bridge
volumes:
    documents_volume:
    chroma_volume:
    sqlite_volume:
