services:
    chroma:
        image: chromadb/chroma:latest
        ports:
            - '8000:8000'
        env_file: .env
        environment:
            - IS_PERSISTENT=TRUE
        networks:
            - schedulrai
        container_name: chroma
        volumes:
            - .chroma_volume:/chroma/chroma

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - '3000:3000'
        container_name: backend
        pull_policy: always
        tty: true
        restart: always
        networks:
            - schedulrai
        env_file: .env
        volumes:
            - .sqlite_volume:/app/data
        environment:
            - CHROMA_SERVER_HOST=chroma
            - OLLAMA_API_BASE=host.docker.internal
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - '80:80'
        container_name: frontend
        networks:
            - schedulrai
        depends_on:
            - backend

networks:
    schedulrai:
        driver: bridge
volumes:
    chroma_volume:
    sqlite_volume:
